#!/usr/bin/php
<?

$version = '0.0.3';

include(dirname(__FILE__).'/utils.d/init.php');

$params = CommandLine::parseArgs($_SERVER['argv']);

$verbose = isset($params['v']);

if(isset($params['version'])){
	throw new version($version);
	return 0;
}

if(isset($params['help'])){
	out('Использование: '.UTIL.' [OPTION] --bin=PATH');
	out('Устанавливает или обновляет команды из пакета rm-server-cmd в директорию PATH.');
	out('Параметры:');
	out(' --bin=PATH  - путь к директории bin пользователя \(например /home/user/bin\).');
	out(' --help      - показать эту справку.');
	out(' --version   - показать версию утилиты.');
	out(' -v          - дебаг.');
	return 0;
}

if(!isset($params['bin']) or $params['bin'] === true){
	throw new error('Не указан --bin=PATH');
}

$base = dirname(__FILE__);
$bin = isset($params['bin']) ? $params['bin'] : null;
checkPath($bin);

$files = glob($base.'/rm-*');
foreach($files as $pth){
	$name = str_replace('.php', '', basename($pth));
	system("ln -fs {$pth} {$bin}/{$name}");
	
	if($verbose){
		out("Создана ссылка для команды {$name}", 'black', UTIL);
	}
}

out("Инициализация завершена.", 'black', UTIL);

include(dirname(__FILE__).'/utils.d/epilog.php');